# Generated by Django 2.2.7 on 2020-09-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('co_name', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bank_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cocat_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='company_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='loan_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prod_policy_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_id', models.BigIntegerField()),
                ('prod_name', models.CharField(max_length=200)),
                ('bank_names', models.CharField(max_length=200)),
                ('type_of_cust', models.CharField(max_length=200)),
                ('salary_acc', models.CharField(max_length=100)),
                ('salary_exist', models.BigIntegerField()),
                ('salary_new', models.BigIntegerField()),
                ('designs', models.CharField(max_length=200)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('current_exp', models.IntegerField()),
                ('roi', models.CharField(max_length=100)),
                ('multiplier', models.CharField(max_length=100)),
                ('foir', models.CharField(max_length=100)),
                ('both', models.CharField(max_length=100)),
                ('eff_date', models.DateField()),
                ('ineff_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_type', models.CharField(max_length=200)),
                ('loan_type', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('co_category', models.CharField(max_length=200)),
                ('loan_co_category', models.CharField(max_length=200)),
                ('gross_salary', models.CharField(max_length=200)),
                ('net_salary', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(max_length=200)),
                ('salary_acc', models.CharField(max_length=200)),
                ('salary_type', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('min_age', models.CharField(max_length=200)),
                ('max_age', models.CharField(max_length=200)),
                ('current_exp', models.CharField(max_length=200)),
                ('total_exp', models.CharField(max_length=200)),
                ('cibil', models.CharField(max_length=200)),
                ('tenure', models.CharField(max_length=200)),
                ('res_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=300)),
                ('rrea', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='residence_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='salary_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_and_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_type', models.CharField(max_length=200)),
                ('loan_type', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('salary_acc', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('min_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('current_exp', models.IntegerField(null=True)),
                ('cibil_scroe', models.IntegerField(null=True)),
                ('roi_from', models.FloatField(null=True)),
                ('roi_to', models.FloatField(null=True)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
                ('cocat_type', models.ManyToManyField(to='crm_app.cocat_type')),
                ('company_type', models.ManyToManyField(to='crm_app.company_type')),
                ('residence_type', models.ManyToManyField(to='crm_app.residence_type')),
                ('salary_type', models.ManyToManyField(to='crm_app.salary_type')),
                ('tenure', models.ManyToManyField(to='crm_app.tenure')),
            ],
        ),
        migrations.CreateModel(
            name='pp_tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_type', models.IntegerField()),
                ('effec_date5', models.DateField()),
                ('ineffec_date5', models.CharField(max_length=100)),
                ('ppid5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_salary_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_type', models.CharField(max_length=200)),
                ('effec_date1', models.DateField()),
                ('ineffec_date1', models.CharField(max_length=100)),
                ('ppid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saltypes', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_residence_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_type', models.CharField(max_length=200)),
                ('effec_date2', models.DateField()),
                ('ineffec_date2', models.CharField(max_length=100)),
                ('ppid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restypes', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_max_age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_type', models.IntegerField()),
                ('effec_date3', models.DateField()),
                ('ineffec_date3', models.CharField(max_length=100)),
                ('ppid3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxages', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_foir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amt', models.BigIntegerField()),
                ('max_amt', models.BigIntegerField()),
                ('cutoff', models.IntegerField()),
                ('ppid7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foirs', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_company_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_type', models.CharField(max_length=200)),
                ('effec_date', models.DateField()),
                ('ineffec_date', models.CharField(max_length=100)),
                ('ppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptypes', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_cocat_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocat_types', models.CharField(max_length=200)),
                ('cocat_no', models.IntegerField()),
                ('min_loan_amt', models.BigIntegerField()),
                ('max_loan_amt', models.BigIntegerField()),
                ('effec_date6', models.DateField()),
                ('ineffec_date6', models.CharField(max_length=100)),
                ('ppid6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocattypes', to='crm_app.prod_policy_master')),
            ],
        ),
        migrations.CreateModel(
            name='pp_cibil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cibil_type', models.IntegerField()),
                ('effec_date4', models.DateField()),
                ('ineffec_date4', models.CharField(max_length=100)),
                ('ppid4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mincibil', to='crm_app.prod_policy_master')),
            ],
        ),
    ]
