# Generated by Django 2.2.7 on 2020-07-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('cibil_score', models.IntegerField()),
                ('bank_name', models.CharField(max_length=200)),
                ('gross_sal', models.IntegerField()),
                ('net_sal', models.IntegerField()),
                ('age', models.IntegerField()),
                ('retire_age', models.IntegerField()),
                ('company_type', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('paid_up_cap', models.IntegerField()),
                ('company_yrs', models.IntegerField()),
                ('nature_company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('designation_type', models.CharField(max_length=200)),
                ('current_exp', models.IntegerField()),
                ('total_exp', models.IntegerField()),
                ('emp_type', models.CharField(max_length=200)),
                ('form_16', models.CharField(max_length=200)),
                ('residence_type', models.CharField(max_length=200)),
                ('stt', models.CharField(max_length=200)),
                ('sttt', models.CharField(max_length=200)),
            ],
        ),
    ]
